@startuml
!include C:\Users\Vpatrushev\IdeaProjects\Diagramms\testForTest\src\d_proc\data_parametres.puml

!include C:\Users\Vpatrushev\IdeaProjects\Diagramms\testForTest\src\fp_proc\fp_action.puml
!include C:\Users\Vpatrushev\IdeaProjects\Diagramms\testForTest\src\fp_proc\fp_legend.puml

!include C:\Users\Vpatrushev\IdeaProjects\Diagramms\testForTest\src\logic_rpoc\logic_action.puml
!include C:\Users\Vpatrushev\IdeaProjects\Diagramms\testForTest\src\logic_rpoc\logic_legend.puml

!include C:\Users\Vpatrushev\IdeaProjects\Diagramms\testForTest\src\d_proc\data_proc.puml

